Add `brew trust` command for Homebrew installation [v/5.7] (#2242)
Backport of https://github.com/hazelcast/hz-docs/pull/2235

[brew changes](https://docs.brew.sh/Tap-Trust) require taps to be
explicitly trusted, else installation is blocked:
```
% brew install hazelcast      
Error: Refusing to load formula hazelcast/hz/hazelcast from untrusted tap hazelcast/hz.
Run `brew trust --formula hazelcast/hz/hazelcast` or `brew trust hazelcast/hz` to trust it.
```

Co-authored-by: Jack Green <jack.green@hazelcast.com>