Update `cluster-utilities`
This documentation seems to be outdated, predating when the command line tool was integrated into platform / MC respectively in https://github.com/hazelcast/hazelcast/pull/20262

Specifically:
- removed references to Management Center as the platform tool does not support that
- Removed Java 8 pre-requisite reference
   - if you try and run with Java 8, it just says  `Unrecognized option: --add-modules
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`
- removed references on _how_ to install it
   - duplicated elsewhere
   - in the following section we refer to `Hazelcast package` and _assume_ users will know how to obtain that
- removed links to the _old_ home of the `hazelcast-command-line` tool