Add `brew trust` command for Homebrew installation
[brew changes](https://docs.brew.sh/Tap-Trust) require taps to be explicitly trusted, else installation is blocked:
```
% brew install hazelcast      
Error: Refusing to load formula hazelcast/hz/hazelcast from untrusted tap hazelcast/hz.
Run `brew trust --formula hazelcast/hz/hazelcast` or `brew trust hazelcast/hz` to trust it.
```